---
- name: Install HAProxy
  ansible.builtin.package:
    name: haproxy
    state: present

- name: Backup HAProxy config
  ansible.builtin.copy:
    src: "{{ haproxy_cfg_path }}"
    dest: "{{ haproxy_cfg_backup_path }}"
    remote_src: yes
    owner: "{{ cfg_owner }}"
    group: "{{ cfg_group }}"
    mode: '0644'

- name: Create HAProxy config
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: "{{ haproxy_cfg_path }}"
    owner: "{{ cfg_owner }}"
    group: "{{ cfg_group }}"
    mode: '0644'